spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC
    username: root
    password: andres_1
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8083
